# Generated by Django 3.1.4 on 2021-01-20 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20210113_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now,
                                    upload_to='recipes/'),
            preserve_default=False,
        ),
    ]
