# Generated by Django 3.1.4 on 2021-01-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20210126_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='favorite_recipe',
            new_name='purchase_recipe',
        ),
    ]
