# Generated by Django 3.1.4 on 2021-01-26 15:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0008_auto_20210126_1422'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchases',
            new_name='ShoppingList',
        ),
    ]
